#!/usr/bin/env python3
"""
This script converts a SBOL file (in N-Triples format) generated by a cell output into a SBML file.

Usage:
    python sbol_to_sbml_converter.py <cell_output_directory>

The script expects that in the provided directory (e.g., 'main.v'), there exists an SBOL file named
'<cell_directory>_ucf._pySBOL3.nt'. It will output an SBML file named '<cell_directory>_ucf._pySBML.xml' in the same directory.

Requirements:
    - sbol3
    - libsbml

Make sure to activate your Python environment and set up the required libraries before running this script.
"""

import os
import sys
import argparse
import subprocess
import sbol3

import libsbml

# add sbol2sbml/sbol2sbml to the path
sys.path.append('sbol2sbml')
sys.path.append('sbol2sbml/sbol2sbml')

from sbol2sbml.converters.sbol2sbml import SBOL2SBML

def convert_sbol_to_sbml(sbol_file, sbml_file, cello_model=False):
    """
    Convert an SBOL file to SBML and save to the specified sbml_file.
    """
    # Use sbol3-to-sbol2 CLI to convert SBOL3 N-Triples to SBOL2 RDF/XML
    sbol_input = sbol_file
    if sbol_input.lower().endswith('.nt'):
        tmp_sbol2 = os.path.splitext(sbol_input)[0] + '_sbol2.xml'
        print(f"Converting SBOL3 N-Triples to SBOL2 RDF/XML at {tmp_sbol2}")
        try:
            subprocess.run(['sbol3-to-sbol2', sbol_input, '-o', tmp_sbol2], check=True)
        except subprocess.CalledProcessError as e:
            print(f"Error converting SBOL3 to SBOL2: {e}")
            sys.exit(1)
        sbol_input = tmp_sbol2
    converter = SBOL2SBML()
    # Determine output directory and target filename
    output_dir, sbml_filename = os.path.split(sbml_file)
    if not output_dir:
        output_dir = '.'
    # Perform conversion (returns dict of models)
    models = converter.convert_sbol_to_sbml(sbol_input, output_dir, cello_model=cello_model)
    print(f"Models: {models}")
    # Save SBML files
    saved_files = converter.save_models(models, output_dir)
    # If only one file generated and its name differs, rename it
    if len(saved_files) == 1:
        gen_file = saved_files[0]
        if gen_file != sbml_file:
            os.rename(gen_file, sbml_file)
            saved_files = [sbml_file]
    print(f"Successfully converted {sbol_file} to {', '.join(saved_files)}")
    return saved_files

def from_run_directory_example():
    import argparse
    parser = argparse.ArgumentParser(description='Convert a cell output SBOL to SBML')
    parser.add_argument('cell_output_dir', help='Directory containing the SBOL file')
    parser.add_argument('--cello', '-c', action='store_true', help='Process as Cello model')
    args = parser.parse_args()
    cell_output_dir = args.cell_output_dir

    if not os.path.isdir(cell_output_dir):
        print(f"Error: {cell_output_dir} is not a valid directory")
        sys.exit(1)

    # Detect SBOL file (N-Triples) in the directory
    nt_files = [f for f in os.listdir(cell_output_dir) if f.lower().endswith('.sbol3.xml')]
    if not nt_files:
        print(f"Error: No SBOL .nt file found in {cell_output_dir}")
        sys.exit(1)
    nt_file = nt_files[0]
    sbol_file = os.path.join(cell_output_dir, nt_file)
    base_name = os.path.splitext(nt_file)[0]
    sbml_file = os.path.join(cell_output_dir, f"{base_name}.xml")

    try:
        saved_files = convert_sbol_to_sbml(sbol_file, sbml_file, cello_model=args.cello)
        # Load and report on each generated SBML file
        for f in saved_files:
            sbml_doc = libsbml.readSBMLFromFile(f)
            print(f"Loaded SBML file {f}: Models={sbml_doc.getNumModels()}, Errors={sbml_doc.getNumErrors()}")
    except Exception as e:
        print(f"Conversion failed: {str(e)}")
        sys.exit(1)

def example_from_file_path(sbol2_file, sbml_file):
    try:
        saved_files = convert_sbol_to_sbml(sbol2_file, sbml_file)
        for f in saved_files:
            sbml_doc = libsbml.readSBMLFromFile(f)
            print(f"Loaded SBML file {f}: Models={sbml_doc.getNumModels()}, Errors={sbml_doc.getNumErrors()}")
    except Exception as e:
        print(f"Conversion failed: {str(e)}")
        sys.exit(1)

if __name__ == "__main__":
    # from_run_directory_example() 
    example_from_file_path('test.xml', 'outputs/cello_outputs/0x17.v/0x17.v_Eco1C1G1T1.UCF.sbml.xml')